# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='nome',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='termo',
            name='tipo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
