# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0014_remove_artigo_favoritos'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='nome',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='estudante',
            name='artigos_favoritos',
            field=models.ManyToManyField(related_name='favorited_by', to='artigos.Artigo'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudante',
            name='ultimo_nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
