# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('exercicio_img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('exercicio_historia', models.TextField(blank=True, null=True)),
                ('exercicio_resposta', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
