# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_de_publicacao', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('introducao', models.TextField(blank=True, null=True)),
                ('intro_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('epidemiologia', models.TextField(blank=True, null=True)),
                ('epidemio_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('classificacao', models.TextField(blank=True, null=True)),
                ('clas_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('etiologia_fisiopatologia', models.TextField(blank=True, null=True)),
                ('etio_top1', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_texto1', models.TextField(blank=True, null=True)),
                ('etio_top2', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_texto2', models.TextField(blank=True, null=True)),
                ('etio_top3', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_texto3', models.TextField(blank=True, null=True)),
                ('etio_top4', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_texto4', models.TextField(blank=True, null=True)),
                ('etio_top5', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_texto5', models.TextField(blank=True, null=True)),
                ('etio_top6', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_texto6', models.TextField(blank=True, null=True)),
                ('etio_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('etio_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.TextField(blank=True, null=True)),
                ('historia_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('exame_fisico', models.TextField(blank=True, null=True)),
                ('ef_top1', models.CharField(blank=True, max_length=200, null=True)),
                ('ef_texto1', models.TextField(blank=True, null=True)),
                ('ef_top2', models.CharField(blank=True, max_length=200, null=True)),
                ('ef_texto2', models.TextField(blank=True, null=True)),
                ('ef_top3', models.CharField(blank=True, max_length=200, null=True)),
                ('ef_texto3', models.TextField(blank=True, null=True)),
                ('ef_top4', models.CharField(blank=True, max_length=200, null=True)),
                ('ef_texto4', models.TextField(blank=True, null=True)),
                ('exames_complementares', models.TextField(blank=True, null=True)),
                ('exames_top1', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_texto1', models.TextField(blank=True, null=True)),
                ('exames_top2', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_texto2', models.TextField(blank=True, null=True)),
                ('exames_top3', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_texto3', models.TextField(blank=True, null=True)),
                ('exames_top4', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_texto4', models.TextField(blank=True, null=True)),
                ('exames_top5', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_texto5', models.TextField(blank=True, null=True)),
                ('exames_top6', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_texto6', models.TextField(blank=True, null=True)),
                ('criterios_diagnosticos', models.TextField(blank=True, null=True)),
                ('diagnostico_diferencial', models.TextField(blank=True, null=True)),
                ('diag_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('top1', models.CharField(blank=True, max_length=200, null=True)),
                ('texto1', models.TextField(blank=True, null=True)),
                ('top1_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('top1_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('tratamento_e_manejo', models.TextField(blank=True, null=True)),
                ('tratamento_nao_medicamentoso', models.TextField(blank=True, null=True)),
                ('tratamento_medicamentoso', models.TextField(blank=True, null=True)),
                ('med_top1', models.CharField(blank=True, max_length=200, null=True)),
                ('med_texto1', models.TextField(blank=True, null=True)),
                ('med_top2', models.CharField(blank=True, max_length=200, null=True)),
                ('med_texto2', models.TextField(blank=True, null=True)),
                ('med_top3', models.CharField(blank=True, max_length=200, null=True)),
                ('med_texto3', models.TextField(blank=True, null=True)),
                ('med_top4', models.CharField(blank=True, max_length=200, null=True)),
                ('med_texto4', models.TextField(blank=True, null=True)),
                ('med_top5', models.CharField(blank=True, max_length=200, null=True)),
                ('med_texto5', models.TextField(blank=True, null=True)),
                ('med_top6', models.CharField(blank=True, max_length=200, null=True)),
                ('med_texto6', models.TextField(blank=True, null=True)),
                ('tratamento_intervencionista', models.TextField(blank=True, null=True)),
                ('trat_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('profilaxia', models.TextField(blank=True, null=True)),
                ('prof_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('prognostico', models.TextField(blank=True, null=True)),
                ('complicacoes', models.TextField(blank=True, null=True)),
                ('algoritmo_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('algoritmo_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('referencias', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
