# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data_pub', models.DateTimeField(blank=True, null=True)),
                ('favoritos', models.IntegerField()),
            ],
        ),
    ]
