# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_remove_artigo_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='data_pub',
            new_name='data_de_publicacao',
        ),
    ]
