# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_auto_20170922_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='intro_top',
            field=models.CharField(blank=True, default='INTRODUÇÃO', max_length=200, null=True),
        ),
    ]
