# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigos', '0003_auto_20170818_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
