# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_auto_20170824_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicioMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('definicao', models.CharField(max_length=50)),
            ],
        ),
    ]
