# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_artigo_intro_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='algoritmo_top',
            field=models.CharField(blank=True, default='ALGORITMO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='class_top',
            field=models.CharField(blank=True, default='CLASSIFICAÇÃO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='complicacoes_top',
            field=models.CharField(blank=True, default='COMPLICAÇÕES', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='criterios_top',
            field=models.CharField(blank=True, default='CRITÉRIOS DIAGNÓSTICOS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='dd_top',
            field=models.CharField(blank=True, default='DIAGNÓSTICO DIFERENCIAL', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='diag_top',
            field=models.CharField(blank=True, default='DIAGNÓSTICO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='ef_top',
            field=models.CharField(blank=True, default='EXAME FÍSICO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='epidemio_top',
            field=models.CharField(blank=True, default='EPIDEMIOLOGIA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='etio_top',
            field=models.CharField(blank=True, default='ETIOLOGIA E FISIOPATOLOGIA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='exames_top',
            field=models.CharField(blank=True, default='EXAMES COMPLEMENTARES', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='historia_top',
            field=models.CharField(blank=True, default='HISTÓRIA CLÍNICA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='medidas_top',
            field=models.CharField(blank=True, default='MEDIDAS GERAIS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='profilaxia_top',
            field=models.CharField(blank=True, default='PROFILAXIA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='prognostico_top',
            field=models.CharField(blank=True, default='PROGNÓSTICO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='referencias_top',
            field=models.CharField(blank=True, default='REFERENCIAS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='trat_int_top',
            field=models.CharField(blank=True, default='TRATAMENTO INTERVENCIONISTA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='trat_med_top',
            field=models.CharField(blank=True, default='TRATAMENTO FARMACOLÓGICO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tratamento_top',
            field=models.CharField(blank=True, default='TRATAMENTO E MANEJO', max_length=200, null=True),
        ),
    ]
