# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_diciofar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasArtigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('artigo1', models.CharField(max_length=50)),
                ('artigo2', models.CharField(max_length=50)),
            ],
        ),
    ]
