# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_auto_20170929_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='intro_texto1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='intro_texto2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='intro_texto3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='intro_texto4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='intro_texto5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='intro_texto6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
