# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0009_delete_diciofar'),
    ]

    operations = [

        migrations.DeleteModel(
            name='DicioMed',
        ),
    ]
