# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0010_auto_20170904_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='texto',
        ),
        migrations.AddField(
            model_name='artigo',
            name='complicacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='criterios_diagnosticos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='epidemiologia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='etiologia_fisiopatologia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='exames_complementares',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='historia_clinica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='introducao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='prognostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tratamento_e_manejo',
            field=models.TextField(blank=True),
        ),
    ]
