# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0010_auto_20171026_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='intro_figura',
            new_name='intro_figura1',
        ),
        migrations.AddField(
            model_name='artigo',
            name='class_texto5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='class_top5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='epidemio_texto5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='epidemio_top5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='intro_figura2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
