# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0011_auto_20171027_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='ef_figura',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
