# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0011_auto_20170904_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='diagnostico_diferencial',
            field=models.TextField(blank=True),
        ),
    ]
