# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0012_artigo_diagnostico_diferencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='favoritos',
            field=models.IntegerField(default=0),
        ),
    ]
