# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0012_artigo_ef_figura'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='algoritmo_img3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
