# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0013_artigo_algoritmo_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='exames_img3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
