# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0013_artigo_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='favoritos',
        ),
    ]
