# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0016_auto_20170907_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='algoritmo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='exame_fisico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='intro_figura',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='profilaxia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tratamento_intervencionista',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tratamento_medicamentoso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tratamento_nao_medicamentoso',
            field=models.TextField(blank=True),
        ),
    ]
