# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0017_auto_20170907_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='algoritmo',
            field=models.ImageField(blank=True, upload_to='static_in_pro/our_static/img'),
        ),
    ]
