# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0019_auto_20170907_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='hitoria_figura',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
