# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0020_artigo_hitoria_figura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='hitoria_figura',
            new_name='historia_figura',
        ),
    ]
