# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0023_termo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaco',
            name='absorcao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='administracao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='alteracaoexames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='classe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='contraindicacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='distribuicao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='eliminacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='farmacocinetica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='farmacodinamica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='gravidez',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='indicacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='lactacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='marcas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='metabolismo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='pediatria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='posologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='rcomum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='rincomum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='rmuitocomum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='rmuitorara',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='rnaodefinida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='rrara',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='subclasse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
