# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0024_auto_20170907_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='introducao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
