# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0026_auto_20170908_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='texto1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='top1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='top1_figura',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
