# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0029_auto_20170912_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='top1_figura',
            new_name='top1_img1',
        ),
        migrations.AddField(
            model_name='artigo',
            name='top1_img2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
