# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0031_auto_20170912_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='algoritmo',
            new_name='algoritmo_img1',
        ),
        migrations.AddField(
            model_name='artigo',
            name='algoritmo_img2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
