# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0033_auto_20170913_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercicio',
        ),
    ]
