# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0034_delete_exercicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Termo',
        ),
    ]
